### ISSUE TITLE
Latest contributions view

### ISSUE THREAD

**Issue by mpetris** [forTEXT/catma#306]
The merging of work contributed by different users can be a time consuming and difficult task. It is easy if every user just worked on Annotations in the Collections of his/her responsibility. But especially delete operations on Tag, Tagsets or Collections with writes from multiple users can complicate a merge substantially. This might make the reversion of commits or the manual resolution of conflicts necessary. 

In an annotation project with the goal of producing annotations for a gold standard or as the basis of down the line analysis procedures this labor intense merging is probably worth the effort. However, if Annotations get produced during a single event tutorial session or as part of a seminar with the goal of comparing the results at the end of that same session then there is often no time to execute a lengthy merge of all contributions. 

Currently all contributions of others that a user sees within the current CATMA session are already merged and pulled into the current branch of the local work tree. This view will be called the "synchronized view".

The "latest contributions view" on the other hand will be a light weight way of comparing contributions to different branches without the need of merging. When switching to this view

 - All branches are fetched.
 - Resources differing from the current branch are detected and loaded read only.
 - The resources are displayed with a color coding:
   - green: resources from the current branch (writable)
   - blue: differing resources from other branches (read only)
 - For modified Tagsets and Collections only the "added" differences are loaded: New or modified Tags, Property definitions, Values, Annotations and Properties.

**Comment by maltem-za** [comment]
**Changes outlined above have now been released with [7.0.0](https://github.com/forTEXT/catma/releases/tag/7.0.0)** - the page [What’s New and Changed in CATMA 7](https://catma.de/documentation/whats-new-and-changed-in-catma-7/) introduces users to the new project view modes, while the page [Upcoming Changes to the Backend Storage Mechanisms and Data Structures](https://catma.de/documentation/access-your-project-data/git-access/upcoming-changes-to-the-backend-storage-mechanisms-and-data-structures/) was created for those who work with raw CATMA data and briefly discusses the new dedicated user branches. Also see #303.
