### ISSUE TITLE
Better feedback about what's going on while the backend is working

### ISSUE THREAD

**Issue by mpetris** [forTEXT/catma#31]
This involves turning on background processing for certain long time processes. Current background processing level is too deep and error prone.

**Comment by maltem-za** [comment]
Closing as this has been resolved to some extent in CATMA 6. Of course there is more that could be done, but we should capture further enhancements as new issues. There has also been some discussion about performing certain operations in a truly asynchronous manner (using GitLab CI tooling, for example).
