### ISSUE TITLE
Could anyone share a precompiled and working war, please?

### ISSUE THREAD

**Issue by fishfree** [forTEXT/catma#341]
I tried many times and no luck :-) Thank you in advance!

**Comment by maltem-za** [comment]
@fishfree You can find a WAR file for CATMA 7.0.4 here (note that no config/properties are included): https://catma.de/wp-content/uploads/2024/01/catma-7.0.4.war
SHA256: bc7d7ead4d68a4f00d7982e71fcaed8f975afab1acc313a60bf5f3f092c47e7e

I've also added something to the [instructions](https://github.com/forTEXT/catma/issues/125#issuecomment-859504069) (SQLite DB).
