### ISSUE TITLE
Support any OAUTH 2 / OIDC server besides Google

### ISSUE THREAD

**Issue by fishfree** [forTEXT/catma#347]
In the [property file](https://github.com/forTEXT/catma/blob/2c00e1ad54bcb88a536d06f623e19a08b060c719/src/main/resources/catma.properties#L42), it seems we can only configure Google Oauth authentication.

**Comment by maltem-za** [comment]
Correct, this is the only supported OAuth2/OIDC provider. Currently there is no plan to add support for others.
