### ISSUE TITLE
What's the default username and password of the pre-compiled war?

### ISSUE THREAD

**Issue by fishfree** [forTEXT/catma#349]
I downloaded the pre-compiled 7.0.4 war file [here](https://catma.de/wp-content/uploads/2024/01/catma-7.0.4.war), and tried login with admin/admin, but it failed with:
![image](https://github.com/forTEXT/catma/assets/1741341/826b8e14-e0f4-45c5-98d1-5c5c0c8624fd)

I also tried  Sign up with the same error as below:
![image](https://github.com/forTEXT/catma/assets/1741341/db15637b-115e-47de-a721-9303f7b562c7)

Attached is the log file: 
[catalina.zip](https://github.com/forTEXT/catma/files/15441087/catalina.zip)

**Comment by maltem-za** [comment]
@fishfree There is no default username and password. All CATMA accounts are controlled by the GitLab backend. The error suggests that `GITLAB_SERVER_URL` is not set in the properties file.

As noted in the [issue about installation instructions](https://github.com/forTEXT/catma/issues/125#issuecomment-859504069), you need to have a GitLab server: "For the GitLab server you can run it locally as a Docker container, or you can use a remote server, but you need to have admin access (and it should be dedicated to CATMA only)."

The [template properties file](https://github.com/forTEXT/catma/raw/master/src/main/resources/catma.properties) explains the different settings. Everything up to the SMTP settings has to be set for CATMA to work. For signup to work, you also need to set all `MAIL_*`, ` GOOGLE_RECAPTCHA_*` and `SIGNUP_TOKEN_KEY` settings.
